/* Host-side table generator.
 *
 * Builds four tables and writes them both as C (tables.h, for the C solver
 * and the host checks) and as RISC-V assembly data (tables.s, for Ripes):
 *
 *   perm_move[5040][9]    permutation rank after each of the 9 moves
 *   orient_move[729][9]   orientation rank after each of the 9 moves
 *   perm_dist[5040]       moves needed to solve the permutation alone
 *   orient_dist[729]      moves needed to solve the orientation alone
 *
 * The two distance tables are pattern databases: each one is an exact BFS
 * over an abstraction of the cube that ignores the other half of the state.
 */
#include <stdio.h>
#include <string.h>

#include "cube.h"

static uint16_t perm_move[PERMUTATIONS][MOVES];
static uint16_t orient_move[ORIENTATIONS][MOVES];
static uint8_t perm_dist[PERMUTATIONS];
static uint8_t orient_dist[ORIENTATIONS];

static void build_move_tables(void)
{
    state_t state;
    /* Rank r * 729 has permutation rank r and every orientation 0. */
    for (uint32_t r = 0; r < PERMUTATIONS; ++r) {
        unrank_state(r * ORIENTATIONS, &state);
        for (uint8_t m = 0; m < MOVES; ++m) {
            state_t next = apply_move(state, m);
            perm_move[r][m] = (uint16_t) (rank_state(&next) / ORIENTATIONS);
        }
    }
    /* Rank r < 729 has the solved permutation and orientation rank r. */
    for (uint32_t r = 0; r < ORIENTATIONS; ++r) {
        unrank_state(r, &state);
        for (uint8_t m = 0; m < MOVES; ++m) {
            state_t next = apply_move(state, m);
            orient_move[r][m] = (uint16_t) (rank_state(&next) % ORIENTATIONS);
        }
    }
}

/* Breadth-first search from rank 0 (solved) over one abstraction. Returns the
 * number of entries reached, which must equal n for a complete table.
 */
static unsigned bfs(const uint16_t *move, uint8_t *dist, unsigned n)
{
    static uint16_t queue[PERMUTATIONS];
    unsigned head = 0, tail = 0;
    memset(dist, 0xFF, n);
    dist[0] = 0;
    queue[tail++] = 0;
    while (head < tail) {
        uint16_t here = queue[head++];
        for (uint8_t m = 0; m < MOVES; ++m) {
            uint16_t there = move[here * MOVES + m];
            if (dist[there] == 0xFF) {
                dist[there] = (uint8_t) (dist[here] + 1);
                queue[tail++] = there;
            }
        }
    }
    return tail;
}

static void print_distribution(const char *name, const uint8_t *dist,
                               unsigned n)
{
    unsigned count[16] = {0}, max = 0;
    for (unsigned i = 0; i < n; ++i) {
        ++count[dist[i]];
        if (dist[i] > max)
            max = dist[i];
    }
    printf("%s: max %u, distribution", name, max);
    for (unsigned d = 0; d <= max; ++d)
        printf(" %u:%u", d, count[d]);
    printf("\n");
}

static int write_c(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f)
        return 0;
    fprintf(f, "/* Generated by gen.c. Do not edit. */\n");
    fprintf(f, "#include <stdint.h>\n\n");
    fprintf(f, "static const uint16_t perm_move[%d][%d] = {\n", PERMUTATIONS,
            MOVES);
    for (unsigned r = 0; r < PERMUTATIONS; ++r) {
        fprintf(f, "    {");
        for (unsigned m = 0; m < MOVES; ++m)
            fprintf(f, "%u%s", perm_move[r][m], m + 1 < MOVES ? ", " : "");
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n\nstatic const uint16_t orient_move[%d][%d] = {\n",
            ORIENTATIONS, MOVES);
    for (unsigned r = 0; r < ORIENTATIONS; ++r) {
        fprintf(f, "    {");
        for (unsigned m = 0; m < MOVES; ++m)
            fprintf(f, "%u%s", orient_move[r][m], m + 1 < MOVES ? ", " : "");
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n\nstatic const uint8_t perm_dist[%d] = {", PERMUTATIONS);
    for (unsigned r = 0; r < PERMUTATIONS; ++r)
        fprintf(f, "%s%u,", r % 30 ? " " : "\n    ", perm_dist[r]);
    fprintf(f, "\n};\n\nstatic const uint8_t orient_dist[%d] = {",
            ORIENTATIONS);
    for (unsigned r = 0; r < ORIENTATIONS; ++r)
        fprintf(f, "%s%u,", r % 30 ? " " : "\n    ", orient_dist[r]);
    fprintf(f, "\n};\n");
    return fclose(f) == 0;
}

static int write_asm(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f)
        return 0;
    fprintf(f, "# Generated by gen.c. Do not edit.\n");
    fprintf(f, "# perm_move/orient_move: row r holds the rank after moves "
               "R R2 R' B B2 B' D D2 D'.\n");
    fprintf(f, "    .data\nperm_move:\n");
    for (unsigned r = 0; r < PERMUTATIONS; ++r) {
        fprintf(f, "    .half");
        for (unsigned m = 0; m < MOVES; ++m)
            fprintf(f, " %u%s", perm_move[r][m], m + 1 < MOVES ? "," : "\n");
    }
    fprintf(f, "orient_move:\n");
    for (unsigned r = 0; r < ORIENTATIONS; ++r) {
        fprintf(f, "    .half");
        for (unsigned m = 0; m < MOVES; ++m)
            fprintf(f, " %u%s", orient_move[r][m], m + 1 < MOVES ? "," : "\n");
    }
    fprintf(f, "perm_dist:\n");
    for (unsigned r = 0; r < PERMUTATIONS; r += 30) {
        fprintf(f, "    .byte");
        for (unsigned i = r; i < r + 30 && i < PERMUTATIONS; ++i)
            fprintf(f, " %u%s", perm_dist[i],
                    i + 1 < r + 30 && i + 1 < PERMUTATIONS ? "," : "\n");
    }
    fprintf(f, "orient_dist:\n");
    for (unsigned r = 0; r < ORIENTATIONS; r += 30) {
        fprintf(f, "    .byte");
        for (unsigned i = r; i < r + 30 && i < ORIENTATIONS; ++i)
            fprintf(f, " %u%s", orient_dist[i],
                    i + 1 < r + 30 && i + 1 < ORIENTATIONS ? "," : "\n");
    }
    return fclose(f) == 0;
}

int main(void)
{
    build_move_tables();
    if (bfs(&perm_move[0][0], perm_dist, PERMUTATIONS) != PERMUTATIONS ||
        bfs(&orient_move[0][0], orient_dist, ORIENTATIONS) != ORIENTATIONS) {
        fputs("pattern database incomplete\n", stderr);
        return 1;
    }
    print_distribution("perm_dist", perm_dist, PERMUTATIONS);
    print_distribution("orient_dist", orient_dist, ORIENTATIONS);
    printf("bytes: perm_move %zu, orient_move %zu, perm_dist %zu, "
           "orient_dist %zu, total %zu\n",
           sizeof perm_move, sizeof orient_move, sizeof perm_dist,
           sizeof orient_dist,
           sizeof perm_move + sizeof orient_move + sizeof perm_dist +
               sizeof orient_dist);
    if (!write_c("tables.h") || !write_asm("tables.s")) {
        fputs("could not write tables\n", stderr);
        return 1;
    }
    return 0;
}
