/* Host-side table generator.
 *
 * Version 1 tables (tables.h, used by search.h and the host checks):
 *
 *   perm_move[5040][9]    permutation rank after each of the 9 moves
 *   orient_move[729][9]   orientation rank after each of the 9 moves
 *   perm_dist[5040]       moves needed to solve the permutation alone
 *   orient_dist[729]      moves needed to solve the orientation alone
 *
 * The two distance tables are pattern databases: each one is an exact BFS
 * over an abstraction of the cube that ignores the other half of the state.
 *
 * Version 2 tables (tables2.h for search2.h, tables.s for Ripes) merge each
 * move table with its distance table into rows of 10 halfwords: entries 0..8
 * point to the row after each move and entry 9 is the distance. The pointers
 * are pre-scaled so that RV32I needs no multiply to follow them:
 *
 *   perm_tab[5040][10]    entries 0..8 hold next_rank * 10, the row's index
 *                         in halfwords (5039 * 20 bytes would not fit 16 bits)
 *   orient_tab[729][10]   entries 0..8 hold next_rank * 20, the row's offset
 *                         in bytes (728 * 20 = 14560 fits)
 */
#include <stdio.h>
#include <string.h>

#include "cube.h"

enum { ROW = 10, DIST = 9 };

static uint16_t perm_move[PERMUTATIONS][MOVES];
static uint16_t orient_move[ORIENTATIONS][MOVES];
static uint8_t perm_dist[PERMUTATIONS];
static uint8_t orient_dist[ORIENTATIONS];
static uint16_t perm_tab[PERMUTATIONS][ROW];
static uint16_t orient_tab[ORIENTATIONS][ROW];

static void build_v2_tables(void)
{
    for (unsigned r = 0; r < PERMUTATIONS; ++r) {
        for (unsigned m = 0; m < MOVES; ++m)
            perm_tab[r][m] = (uint16_t) (perm_move[r][m] * ROW);
        perm_tab[r][DIST] = perm_dist[r];
    }
    for (unsigned r = 0; r < ORIENTATIONS; ++r) {
        for (unsigned m = 0; m < MOVES; ++m)
            orient_tab[r][m] = (uint16_t) (orient_move[r][m] * ROW * 2);
        orient_tab[r][DIST] = orient_dist[r];
    }
}

static void write_rows(FILE *f, const char *name, const uint16_t *tab,
                       unsigned rows, unsigned cols)
{
    fprintf(f, "static const uint16_t %s[%u][%u] = {\n", name, rows, cols);
    for (unsigned r = 0; r < rows; ++r) {
        fprintf(f, "    {");
        for (unsigned c = 0; c < cols; ++c)
            fprintf(f, "%u%s", tab[r * cols + c], c + 1 < cols ? ", " : "");
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n");
}

static void write_rows_asm(FILE *f, const char *name, const uint16_t *tab,
                           unsigned rows, unsigned cols)
{
    fprintf(f, "%s:\n", name);
    for (unsigned r = 0; r < rows; ++r) {
        fprintf(f, "    .half");
        for (unsigned c = 0; c < cols; ++c)
            fprintf(f, " %u%s", tab[r * cols + c], c + 1 < cols ? "," : "\n");
    }
}

static void build_move_tables(void)
{
    state_t state;
    /* Rank r * 729 has permutation rank r and every orientation 0. */
    for (uint32_t r = 0; r < PERMUTATIONS; ++r) {
        unrank_state(r * ORIENTATIONS, &state);
        for (uint8_t m = 0; m < MOVES; ++m) {
            state_t next = apply_move(state, m);
            perm_move[r][m] = (uint16_t) (rank_state(&next) / ORIENTATIONS);
        }
    }
    /* Rank r < 729 has the solved permutation and orientation rank r. */
    for (uint32_t r = 0; r < ORIENTATIONS; ++r) {
        unrank_state(r, &state);
        for (uint8_t m = 0; m < MOVES; ++m) {
            state_t next = apply_move(state, m);
            orient_move[r][m] = (uint16_t) (rank_state(&next) % ORIENTATIONS);
        }
    }
}

/* Breadth-first search from rank 0 (solved) over one abstraction. Returns the
 * number of entries reached, which must equal n for a complete table.
 */
static unsigned bfs(const uint16_t *move, uint8_t *dist, unsigned n)
{
    static uint16_t queue[PERMUTATIONS];
    unsigned head = 0, tail = 0;
    memset(dist, 0xFF, n);
    dist[0] = 0;
    queue[tail++] = 0;
    while (head < tail) {
        uint16_t here = queue[head++];
        for (uint8_t m = 0; m < MOVES; ++m) {
            uint16_t there = move[here * MOVES + m];
            if (dist[there] == 0xFF) {
                dist[there] = (uint8_t) (dist[here] + 1);
                queue[tail++] = there;
            }
        }
    }
    return tail;
}

static void print_distribution(const char *name, const uint8_t *dist,
                               unsigned n)
{
    unsigned count[16] = {0}, max = 0;
    for (unsigned i = 0; i < n; ++i) {
        ++count[dist[i]];
        if (dist[i] > max)
            max = dist[i];
    }
    printf("%s: max %u, distribution", name, max);
    for (unsigned d = 0; d <= max; ++d)
        printf(" %u:%u", d, count[d]);
    printf("\n");
}

static int write_c(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f)
        return 0;
    fprintf(f, "/* Generated by gen.c. Do not edit. */\n");
    fprintf(f, "#include <stdint.h>\n\n");
    fprintf(f, "static const uint16_t perm_move[%d][%d] = {\n", PERMUTATIONS,
            MOVES);
    for (unsigned r = 0; r < PERMUTATIONS; ++r) {
        fprintf(f, "    {");
        for (unsigned m = 0; m < MOVES; ++m)
            fprintf(f, "%u%s", perm_move[r][m], m + 1 < MOVES ? ", " : "");
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n\nstatic const uint16_t orient_move[%d][%d] = {\n",
            ORIENTATIONS, MOVES);
    for (unsigned r = 0; r < ORIENTATIONS; ++r) {
        fprintf(f, "    {");
        for (unsigned m = 0; m < MOVES; ++m)
            fprintf(f, "%u%s", orient_move[r][m], m + 1 < MOVES ? ", " : "");
        fprintf(f, "},\n");
    }
    fprintf(f, "};\n\nstatic const uint8_t perm_dist[%d] = {", PERMUTATIONS);
    for (unsigned r = 0; r < PERMUTATIONS; ++r)
        fprintf(f, "%s%u,", r % 30 ? " " : "\n    ", perm_dist[r]);
    fprintf(f, "\n};\n\nstatic const uint8_t orient_dist[%d] = {",
            ORIENTATIONS);
    for (unsigned r = 0; r < ORIENTATIONS; ++r)
        fprintf(f, "%s%u,", r % 30 ? " " : "\n    ", orient_dist[r]);
    fprintf(f, "\n};\n");
    return fclose(f) == 0;
}

static int write_c2(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f)
        return 0;
    fprintf(f, "/* Generated by gen.c. Do not edit. See gen.c for the layout. "
               "*/\n#include <stdint.h>\n\n");
    write_rows(f, "perm_tab", &perm_tab[0][0], PERMUTATIONS, ROW);
    fprintf(f, "\n");
    write_rows(f, "orient_tab", &orient_tab[0][0], ORIENTATIONS, ROW);
    return fclose(f) == 0;
}

static int write_asm(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f)
        return 0;
    fprintf(f, "# Generated by gen.c. Do not edit.\n"
               "# Rows of 10 halfwords: entries 0..8 follow moves "
               "R R2 R' B B2 B' D D2 D',\n"
               "# entry 9 is the pattern-database distance.\n"
               "# perm_tab entries hold next_rank * 10 (row index in "
               "halfwords);\n"
               "# orient_tab entries hold next_rank * 20 (row offset in "
               "bytes).\n"
               "    .data\n");
    write_rows_asm(f, "perm_tab", &perm_tab[0][0], PERMUTATIONS, ROW);
    write_rows_asm(f, "orient_tab", &orient_tab[0][0], ORIENTATIONS, ROW);
    return fclose(f) == 0;
}

int main(void)
{
    build_move_tables();
    if (bfs(&perm_move[0][0], perm_dist, PERMUTATIONS) != PERMUTATIONS ||
        bfs(&orient_move[0][0], orient_dist, ORIENTATIONS) != ORIENTATIONS) {
        fputs("pattern database incomplete\n", stderr);
        return 1;
    }
    build_v2_tables();
    print_distribution("perm_dist", perm_dist, PERMUTATIONS);
    print_distribution("orient_dist", orient_dist, ORIENTATIONS);
    printf("v1 bytes: perm_move %zu, orient_move %zu, perm_dist %zu, "
           "orient_dist %zu, total %zu\n",
           sizeof perm_move, sizeof orient_move, sizeof perm_dist,
           sizeof orient_dist,
           sizeof perm_move + sizeof orient_move + sizeof perm_dist +
               sizeof orient_dist);
    printf("v2 bytes: perm_tab %zu, orient_tab %zu, total %zu\n",
           sizeof perm_tab, sizeof orient_tab,
           sizeof perm_tab + sizeof orient_tab);
    if (!write_c("tables.h") || !write_c2("tables2.h") ||
        !write_asm("tables.s")) {
        fputs("could not write tables\n", stderr);
        return 1;
    }
    return 0;
}
